config/routes.rb
Rails.application.routes.draw do
  root to: 'authentication#index'

  # Login and Sign-up routes
  post '/signup', to: 'users#new'
  get '/auth/:provider/callback', to: 'sessions#create_social'
  post '/authentication', to: 'sessions#create_conventional'
  delete '/logout', to: 'sessions#destroy'

  # Search route
  post 'search', to: 'static_pages#search'

  # Imprint route
  post 'imprint', to: 'static_pages#imprint'

  # Search partial routes
  post 'filter_user', to: 'static_pages#user_filter'
  post 'filter_playlist', to: 'static_pages#playlist_filter'

  # Add Song to Playlist route
  post 'add_to_playlist', to: 'static_pages#add_to_playlist'

  resources :users
  resources :playlists
  resources :songs
  resources :tracks

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :check_login_state

  def search
    if params[:search]
      session[:users_filtered] = User.search(params[:search]).order('created_at DESC')
      session[:playlists_filtered] = Playlist.search(params[:search]).order('created_at DESC')
    else
      session[:users_filtered] = User.all.order('created_at DESC')
      session[:playlists_filtered] = Playlist.all.order('created_at DESC')
    end
  end

  def user_filter
    respond_to do |format|
      format.js { render 'static_pages/user_filter.js.erb' }
    end
  end

  def playlist_filter
    respond_to do |format|
      format.js { render 'static_pages/playlist_filter.js.erb' }
    end
  end

  def add_to_playlist
    s = Song.create(titel: params[:title],
                    source: params[:source],
                    thumbnail_url: params[:thumbnail_url],
                    song_url: params[:song_url],
                    host: params[:host],
                    year: DateTime.now.in_time_zone
                   )
    pos = Track.where('playlist_id = ?', params[:playlist_id]).count + 1
    Track.create(position: pos, playlist_id: params[:playlist_id], song_id: s.id)
    redirect_to user_path(session[:user_id])
  end
end

app/views/static_pages/_playlist_filter.html.erb
<% if playlists_filtered.present? %>

  <ul>
    <% playlists_filtered.each do |playlist| %>
      <li>
        <%= link_to playlist_path(playlist["id"]) do %>
          <%= image_tag "pl-placeholder.png", alt: playlist["name"], class: "tn" %>
        <% end %>
        <span class="first"><%= link_to playlist["name"], playlist_path(playlist["id"]) %></span>
      </li>
    <% end %>
  </ul>


<% else %>
<p>No Playlists found...</p>
<% end %>

app/views/static_pages/_playlists.html.erb
<p>Add to Playlist:</p>

<% if current_user.playlists.present? %>
  <ul>
    <% current_user.playlists.each do |p| %>
      <li class="pl" data-playlist_id="<%= p.id %>">
        <%= p.name %>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/static_pages/_user_filter.html.erb
<% if users_filtered.present? %>

  <ul>
    <% users_filtered.each do |user| %>
      <li>
        <%= link_to user_path(user["id"]) do %>
          <% if user["image_url"] == nil %>
              <%= image_tag gravatar_image_url(user["email"]), alt: user["name"], class: 'tn' %>
          <% else %>
              <%= image_tag user["image_url"], alt: user["name"], class: 'tn' %>
          <% end %>
        <% end %>
        <span class="first">
          <%= link_to user["name"], user_path(user["id"]) %>
        </span>
        <span><%= user["email"] %></span>
      </li>
    <% end %>
  </ul>
<% else %>
<p>No Users found...</p>
<% end %>

app/views/static_pages/imprint.html.erb
<div class="container-fluid imprint">
    <div class="imprint-container col-xs-12 col-sm-8 col-md-8 col-lg-6 center-block">
      <p class="text-center moosic">moosic</p>
      <div class="container-fluid">
        <div class="row">
          <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
            <%= image_tag "logo-fh.png", class: "img-responsive", id: "fh", alt: "FH-Salzburg" %>
          </div>
          <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
            <%= image_tag "logo-mmt.png", class: "img-responsive", alt: "MultiMediaTechnology" %>
          </div>
        </div>
      </div>
      <p class="text-center mmp">multimedia project 2a by</p>
      <div class="container-fluid info">
        <div class="row col-md-12 col-lg-12">
          <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
            <p class="text-center">Michael Andorfer</p>
            <p class="text-center">mandorfer.mmt-b2014@fh-salzburg.ac.at</p>
          </div>
          <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
            <p class="text-center">Bernhard Steger</p>
            <p class="text-center">bsteger.mmt-b2013@fh-salzburg.ac.at</p>
          </div>
        </div>
      </div>
    </div>
</div>

app/views/static_pages/playlist_filter.js.erb
$('#result-container').html("<%= j render 'static_pages/playlist_filter', :playlists_filtered => session[:playlists_filtered] %>");

app/views/static_pages/search.html.erb
<script src="https://apis.google.com/js/client.js?onload=onClientLoad" type="text/javascript"></script>
<div class="container-fluid wrapper">
  <div class="row col-xs-12">
  </div>
  <div class="row col-xs-12">
    <div class="filter-menu col-md-4 col-lg-3">
      <ul class="list-unstyled">
        <li id="tracks">
          <%= image_tag "track.png", alt: "track", class: "menu-icon"%>
          Tracks
        </li>
        <li id="playlists">
          <%= image_tag "playlist.png", alt: "playlist", class: "menu-icon" %>
          <%= link_to "Playlists", filter_playlist_path, :remote => true, method: :post %>
        </li>
        <li id="users">
          <%= image_tag "user.png", alt: "user", class: "menu-icon" %>
          <%= link_to "Users", filter_user_path, :remote => true, method: :post %>
        </li>
      </ul>
    </div>
    <div class="playlist-popup hidden">
      <%= render "playlists" %>
      <p class="text-right"><span class="cancel">cancel</span></p>
    </div>
    <div id="result-container" class="col-md-8 col-lg-6">
    </div>
  </div>
</div>

app/views/static_pages/user_filter.js.erb
$('#result-container').html("<%= j render 'static_pages/user_filter', :users_filtered => session[:users_filtered] %>");