config/routes.rb
Rails.application.routes.draw do
  root to: 'authentication#index'

  # Login and Sign-up routes
  post '/signup', to: 'users#new'
  get '/auth/:provider/callback', to: 'sessions#create_social'
  post '/authentication', to: 'sessions#create_conventional'
  delete '/logout', to: 'sessions#destroy'

  # Search route
  post 'search', to: 'static_pages#search'

  # Imprint route
  post 'imprint', to: 'static_pages#imprint'

  # Search partial routes
  post 'filter_user', to: 'static_pages#user_filter'
  post 'filter_playlist', to: 'static_pages#playlist_filter'

  # Add Song to Playlist route
  post 'add_to_playlist', to: 'static_pages#add_to_playlist'

  resources :users
  resources :playlists
  resources :songs
  resources :tracks

end

app/models/song.rb
class Song < ActiveRecord::Base
  has_many :tracks, dependent: :destroy
  has_many :playlists, through: :tracks
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :check_login_state, only: [:index]
  before_action :set_song, only: [:show, :edit, :update, :destroy]

  # GET /songs
  # GET /songs.json
  def index
    # Single track
    if params[:singletrack] == 'true'
      # Create a new song with needed attributes from url parameters
      song = Song.new
      song.song_url = params[:songurl]
      song.host = params[:songhost]

      # Make song available in javascript
      gon.current_song = song
    else # Playlist
      # Get playlist according to url parameter
      current_user = User.find(session[:user_id])
      @playlist = current_user.playlists.find(params[:playlist])

      # Get all tracks of that playlist ascending ordered by their position
      tracks = Track.where('playlist_id = ?', params[:playlist]).order(position: :asc).all

      # Get all songs of that playlist
      @songs = []
      tracks.each do |track|
        song = Song.where('id = ?', track.song_id).first
        @songs << song if song
      end

      # Make playlists, songs, count of songs and startposition available in javascript
      gon.current_playlist = @playlist
      gon.current_playlist_songs = @songs
      gon.current_playlist_count_songs = Playlist.find(params[:playlist]).songs.size
      gon.current_position = params[:startposition]
      gon.single_track = params[:singletrack]
    end
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
  end

  # GET /songs/new
  def new
    @song = Song.new
  end

  # GET /songs/1/edit
  def edit
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(song_params)

    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: 'Song was successfully created.' }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1
  # PATCH/PUT /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song.destroy
    respond_to do |format|
      format.html { redirect_to songs_url, notice: 'Song was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_song
    @song = Song.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def song_params
    params.require(:song).permit(:titel, :source, :thumbnail_url, :song_url, :host, :year)
  end
end

app/views/songs/_form.html.erb
<%= form_for(@song) do |f| %>
  <% if @song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@song.errors.count, 'error') %> prohibited this song from being saved:</h2>
      <ul>
      <% @song.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titel %><br>
    <%= f.text_field :titel %>
  </div>
  <div class="field">
    <%= f.label :source %><br>
    <%= f.text_field :source %>
  </div>
  <div class="field">
    <%= f.label :thumbnail_url %><br>
    <%= f.text_field :thumbnail_url %>
  </div>
  <div class="field">
    <%= f.label :song_url %><br>
    <%= f.text_field :song_url %>
  </div>
  <div class="field">
    <%= f.label :host %><br>
    <%= f.text_field :host %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.date_select :year %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/songs/edit.html.erb
<h1>Editing Song</h1>

<%= render 'form' %>

<%= link_to 'Show', @song %> |
<%= link_to 'Back', songs_path %>

app/views/songs/index.html.erb
<div class="container-fluid player">
  <div class="row center-vertical">
    <div class="row col-xs-12 col-sm-12 col-md-12 col-lg-12 center-block players">
      <div id="yt-widget" style="display: none"></div>
      <iframe id="sc-widget" width="640" height="390" scrolling="no" frameborder="no" style="display: none" src="https://w.soundcloud.com/player/?url=http%3A%2F%2Fapi.soundcloud.com%2Ftracks%2F1848538&show_artwork=false"></iframe>
    </div>
    <div class="row controls">
      <div class="controls-container col-xs-4 col-sm-3 col-md-2 col-lg-2 center-block">
        <div id="prev-song" class="prev-song col-xs-3 col-sm-3 col-md-3 col-lg-3"></div>
        <div id="toggle-song" class="pause-song col-xs-3 col-sm-3 col-md-3  col-lg-3"></div>
        <div id="next-song" class="next-song col-xs-3 col-sm-3 col-md-3  col-lg-3"></div>
      </div>
    </div>
  </div>
</div>

app/views/songs/new.html.erb
<h1>New Song</h1>

<%= render 'form' %>

<%= link_to 'Back', songs_path %>

app/views/songs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titel:</strong>
  <%= @song.titel %>
</p>

<p>
  <strong>Source:</strong>
  <%= @song.source %>
</p>

<p>
  <strong>Thumbnail url:</strong>
  <%= @song.thumbnail_url %>
</p>

<p>
  <strong>Song url:</strong>
  <%= @song.song_url %>
</p>

<p>
  <strong>Host:</strong>
  <%= @song.host %>
</p>

<p>
  <strong>Year:</strong>
  <%= @song.year %>
</p>

<%= link_to 'Edit', edit_song_path(@song) %> |
<%= link_to 'Back', songs_path %>