config/routes.rb
Rails.application.routes.draw do
  root to: 'authentication#index'

  # Login and Sign-up routes
  post '/signup', to: 'users#new'
  get '/auth/:provider/callback', to: 'sessions#create_social'
  post '/authentication', to: 'sessions#create_conventional'
  delete '/logout', to: 'sessions#destroy'

  # Search route
  post 'search', to: 'static_pages#search'

  # Imprint route
  post 'imprint', to: 'static_pages#imprint'

  # Search partial routes
  post 'filter_user', to: 'static_pages#user_filter'
  post 'filter_playlist', to: 'static_pages#playlist_filter'

  # Add Song to Playlist route
  post 'add_to_playlist', to: 'static_pages#add_to_playlist'

  resources :users
  resources :playlists
  resources :songs
  resources :tracks

end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
  belongs_to :user
  has_many :tracks, dependent: :destroy
  has_many :songs, through: :tracks

  attr_accessor :image_url
  attr_accessor :count_songs

  def self.search(query)
    where('name LIKE ?', "%#{query}%")
  end
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  before_action :check_login_state, only: [:show, :edit]
  before_action :set_playlist, only: [:show, :edit, :update, :destroy]

  # GET /playlists
  # GET /playlists.json
  def index
    @playlists = Playlist.all
  end

  # GET /playlists/1
  # GET /playlists/1.json
  def show
  end

  # GET /playlists/new
  def new
    @playlist = Playlist.new
  end

  # GET /playlists/1/edit
  def edit
  end

  # POST /playlists
  # POST /playlists.json
  def create
    @playlist = Playlist.new(playlist_params)

    respond_to do |format|
      if @playlist.save
        format.html { redirect_to @playlist, notice: 'Playlist was successfully created.' }
        format.json { render :show, status: :created, location: @playlist }
      else
        format.html { render :new }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /playlists/1
  # PATCH/PUT /playlists/1.json
  def update
    respond_to do |format|
      if @playlist.update(playlist_params)
        format.html { redirect_to @playlist, notice: 'Playlist was successfully updated.' }
        format.json { render :show, status: :ok, location: @playlist }
      else
        format.html { render :edit }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /playlists/1
  # DELETE /playlists/1.json
  def destroy
    @playlist.destroy
    respond_to do |format|
      format.html { redirect_to user_path(session[:user_id]), notice: 'Playlist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_playlist
    current_user = User.find(session[:user_id])
    @playlist = current_user.playlists.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def playlist_params
    params.require(:playlist).permit(:name, :user_id)
  end
end

app/views/playlists/_form.html.erb
<%= form_for(@playlist) do |f| %>
  <% if @playlist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@playlist.errors.count, "error") %> prohibited this playlist from being saved:</h2>
      <ul>
      <% @playlist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :name %>
  </div>
  <%= f.hidden_field :user_id, :value => current_user.id %>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/playlists/edit.html.erb
<h1>Editing Playlist</h1>

<%= render 'form' %>

<%= link_to 'Show', @playlist %> |
<%= link_to 'Back', playlists_path %>

app/views/playlists/index.html.erb
<h1>Playlists</h1>
<div class="visible-xs-block">
  <% @playlists.each_slice(1).with_index do |playlist_slice, i| %>
    <div class="row col-xs-12">
      <% playlist_slice.each do |playlist| %>
        <div class="col-xs-12">
          <%= link_to(playlist) do %>
            <div class="tile">
              <%= image_tag playlist.image_url, alt: playlist.name, class: 'center-block' %>
              <h4><%= playlist.name %></h4>
              <p class="create-date">created on <%= l playlist.created_at, format: :european_format %></p>
              <p class="count-songs"><%= playlist.tracks.count %> songs</p>
            </div>
          <% end %>
        </div>
        <% if i == @playlists.length / 1 && playlist == playlist_slice.last %>
          <div class="col-xs-12">
            <%= link_to(new_playlist_path) do %>
              <div class="tile">
                <%= image_tag 'add.png', alt: 'playlist add', class: 'center-block' %>
                <h4>Add a new playlist</h4>
              </div>
            <% end %>
          </div>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

<div class="visible-sm-block">
  <% @playlists.each_slice(2).with_index do |playlist_slice, i| %>
    <div class="row col-sm-12">
      <% playlist_slice.each do |playlist| %>
        <div class="col-sm-6">
          <%= link_to(playlist) do %>
            <div class="tile">
              <%= image_tag playlist.image_url, alt: playlist.name, class: 'center-block' %>
              <h4><%= playlist.name %></h4>
              <p class="create-date">created on <%= l playlist.created_at, format: :european_format %></p>
              <p class="count-songs"><%= playlist.tracks.count %> songs</p>
            </div>
          <% end %>
        </div>
        <% if i == @playlists.length / 2 && playlist == playlist_slice.last %>
          <div class="col-sm-6">
            <%= link_to(new_playlist_path) do %>
              <div class="tile">
                <%= image_tag 'add.png', alt: 'playlist add', class: 'center-block' %>
                <h4>Add a new playlist</h4>
              </div>
            <% end %>
          </div>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

<div class="visible-md-block">
  <% @playlists.each_slice(2).with_index do |playlist_slice, i| %>
    <div class="row col-md-12">
      <% playlist_slice.each do |playlist| %>
        <div class="col-md-6">
          <%= link_to(playlist) do %>
            <div class="tile">
              <%= image_tag playlist.image_url, alt: playlist.name, class: 'center-block' %>
              <h4><%= playlist.name %></h4>
              <p class="create-date">created on <%= l playlist.created_at, format: :european_format %></p>
              <p class="count-songs"><%= playlist.tracks.count %> songs</p>
            </div>
          <% end %>
        </div>
        <% if i == @playlists.length / 2 && playlist == playlist_slice.last %>
          <div class="col-md-6">
            <%= link_to(new_playlist_path) do %>
              <div class="tile">
                <%= image_tag 'add.png', alt: 'playlist add', class: 'center-block' %>
                <h4>Add a new playlist</h4>
              </div>
            <% end %>
          </div>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

<div class="visible-lg-block">
  <% @playlists.each_slice(3).with_index do |playlist_slice, i| %>
    <div class="row col-lg-12">
      <% playlist_slice.each do |playlist| %>
        <div class="col-lg-4">
          <%= link_to(playlist) do %>
            <div class="tile">
              <%= image_tag playlist.image_url, alt: playlist.name, class: 'center-block' %>
              <h4><%= playlist.name %></h4>
              <p class="create-date">created on <%= l playlist.created_at, format: :european_format %></p>
              <p class="count-songs"><%= playlist.tracks.count %> songs</p>
            </div>
          <% end %>
        </div>
        <% if i == @playlists.length / 3 && playlist == playlist_slice.last %>
          <div class="col-lg-4">
            <%= link_to(new_playlist_path) do %>
              <div class="tile">
                <%= image_tag 'add.png', alt: 'playlist add', class: 'center-block' %>
                <h4>Add a new playlist</h4>
              </div>
            <% end %>
          </div>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/playlists/new.html.erb
<div class="playlist-header">
  <span>Name Your new Playlist</span>

<%= render 'form' %>
<br>
<%= link_to 'Back to Playlists', user_path(session[:user_id]) %>

</div>

app/views/playlists/show.html.erb
<div class="playlist-header">
  <span><%= @playlist.name %></span>
  <% if @playlist.user == current_user %>
    <%= link_to @playlist, method: :delete, data: { confirm: 'Are you sure?' } do %>
      <%= image_tag 'trash.png' %>
    <% end %>
  <% end %>

  <% if @playlist.tracks.present? %>
    <%= link_to songs_path(:playlist => @playlist.id, :startposition => 1, :singletrack => false) , :target => '_blank' do %>
      <%= image_tag 'play.png' %>
    <% end %>
  <% end %>
</div>

<div class="container-fluid">
  <% if @playlist.tracks.present? %>
  <ul class="songlist col-xs-12 col-sm-12 col-md-6 col-lg-6">
    <% @playlist.tracks.each do |t| %>
      <li>
        <%= link_to(songs_path(:songurl => t.song.song_url, :songhost => t.song.host, :singletrack => true), :target => '_blank') do %>
          <% if t.song.thumbnail_url.present? %>
            <%= image_tag t.song.thumbnail_url %>
          <%else %>
            <%= image_tag 'sc-placeholder.png' %>
          <% end %>
          <div>
            <span><%= t.song.titel %></span><br>
            <span><%= t.song.source %></span>
          </div>
        <% end %>
        <% if @playlist.user == current_user %>
          <span class="delete" ><%= link_to 'Delete', t, method: :delete, data: { confirm: 'Are you sure?' } %></span>
        <% end %>
      </li>
    <% end %>
  </ul>
  <% else %>
    <p>No Songs in this Playlist!</p>
  <% end %>
</div>

<div class="playlist-header">
  <%= link_to 'Back to Playlists', :back %>
</div>