config/routes.rb
Rails.application.routes.draw do
  root to: 'authentication#index'

  # Login and Sign-up routes
  post '/signup', to: 'users#new'
  get '/auth/:provider/callback', to: 'sessions#create_social'
  post '/authentication', to: 'sessions#create_conventional'
  delete '/logout', to: 'sessions#destroy'

  # Search route
  post 'search', to: 'static_pages#search'

  # Imprint route
  post 'imprint', to: 'static_pages#imprint'

  # Search partial routes
  post 'filter_user', to: 'static_pages#user_filter'
  post 'filter_playlist', to: 'static_pages#playlist_filter'

  # Add Song to Playlist route
  post 'add_to_playlist', to: 'static_pages#add_to_playlist'

  resources :users
  resources :playlists
  resources :songs
  resources :tracks

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Moosic</title>
  <script src="https://connect.soundcloud.com/sdk/sdk-3.0.0.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= include_gon %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if current_user %>
<div class="user-profile-header col-xs-12 col-sm-12 col-md-12 col-lg-12">
  <div class="col-xs-12 col-sm-4 col-md-4 col-lg 4">
    <%= image_tag('logo-moosic.png', width: 48, height: 48) %>
    <span class="logo-text">moosic</span>
  </div>
  <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
    <%= form_tag('/search', method: 'post') do |f| %>
    <div class="input-container">
      <div class="field">
        <div class="inner right">
          <i class="glyphicon glyphicon-search"></i>
          <%= form_tag search_path, :method => :post do %>
            <%= text_field_tag :search, params[:search], class: 'search-field form-control', id: 'search_input', placeholder: 'Search...' %>
          <% end %>
        </div>
      </div>
    </div>
<% end %>
  </div>

  <div class="hidden-xs col-sm-1 col-md-1 col-lg-2">
    <p class="imprint"><%= link_to "Imprint", imprint_path, method: :post %></p>
  </div>

  <%= link_to user_path(current_user) do %>
  <div class="user-info-top hidden-xs col-sm-3 col-md-3 col-lg-2">
    <div class="float-right">
      <p><%= current_user.name.downcase %></p>
      <% if current_user.image_url == nil %>
          <%= image_tag gravatar_image_url(current_user.email), alt: current_user.name, class: 'img-circle-small', width: 48, height: 48 %>
      <% else %>
          <%= image_tag current_user.image_url, alt: current_user.name, class: 'img-circle-small', width: 48, height: 48 %>
      <% end %>
    </div>
  </div>
  <% end %>
  <div class="user-menu">
    <ul>
      <% if current_user.image_url == nil %>
        <li><%= link_to 'Settings', edit_user_path(current_user) %></li>
      <% else %>
          <li><%= link_to 'Settings (not available with Social Login)', user_path(current_user) %></li>
      <% end %>
      <li><%= link_to 'Logout', logout_path, method: :delete %></li>
    </ul>
  </div>
</div>
<% end %>

<%= yield %>

</body>
</html>